language: rust
sudo: false
cache: cargo
rust:
- nightly
- 1.13.0
matrix:
  include:
  - os: osx
    rust: 1.13.0
    osx_image: xcode9
  - os: osx
    rust: 1.13.0
    osx_image: xcode8
  - os: osx
    rust: 1.13.0
    osx_image: xcode6.4
env:
- RUST_BACKTRACE=1 RUST_TEST_THREADS=1
script:
- cargo test
- rustdoc --test README.md -L target/debug/deps -L target/debug
